import type { Metadata } from "next";
import { unstable_setRequestLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import { LocaleType } from "@/shared/types/locale";
import { NextIntlClientProvider, useMessages } from "next-intl";
import "@/shared/assets/css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: LocaleType };
}>) {
  const messages = useMessages();
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <main className="container mx-auto px-4">{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
