import type { Metadata } from "next";
import { unstable_setRequestLocale } from "next-intl/server";
import { LocaleType } from "@/shared/types/locale";
import { NextIntlClientProvider, useMessages } from "next-intl";
import "@/shared/assets/css/globals.css";
import ReactQueryProvider from "@/shared/lib/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: "https://simaat.app/wp-content/uploads/2022/11/favicon-32x32-1.png",
};

export type RootLayoutProps = {
  params: { locale: LocaleType };
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: LocaleType };
}>) {
  const messages = useMessages();
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body suppressHydrationWarning={true}>
        <NextIntlClientProvider messages={messages}>
          <ReactQueryProvider>
            <main>{children}</main>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
