import { LocaleType } from "@/shared/types/locale";
import { unstable_setRequestLocale } from "next-intl/server";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: LocaleType };
}) {
  unstable_setRequestLocale(locale);

  return children;
}
